spring:
  datasource:
    url: jdbc:mysql://120.46.159.231:3306/2022212869
    username: 2022212869
    password: 2022212869
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com:
      example: debug
    sql: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
my:
  secretkey: R28K42ZEJ8LWRHU5